### ISSUE TITLE
celery 실행

### ISSUE THREAD

**Issue by kimdoori** [Doo-Python-Study/Celery-Sample#3]

**Comment by kimdoori** [comment]
`celery -A tasks worker --loglevel=info` 명령 시 에러 발생
```
2018-11-18 11:23:44,044: CRITICAL/MainProcess] Unrecoverable error: SyntaxError('invalid syntax', ('/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/celery/backends/redis.py', 22, 19, 'from . import async, base\n'))
Traceback (most recent call last):
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

```

**Comment by kimdoori** [comment]
<https://github.com/celery/celery/pull/4852> 참고

**Comment by kimdoori** [comment]
Adjust imports of async
```
vim redis.py
vim celery/backends/rpc.py
```

**Comment by kimdoori** [comment]
테스트 코드 진행 시 에러 발생
```
 [2018-11-18 11:45:18,393: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'float' object has no attribute 'items'")
Traceback (most recent call last):
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/kombu/transport/redis.py", line 1040, in on_readable
    self.cycle.on_readable(fileno)
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/kombu/transport/redis.py", line 724, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
    callback(message)
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 632, in _callback
    self.qos.append(message, message.delivery_tag)
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/kombu/transport/redis.py", line 149, in append
    pipe.zadd(self.unacked_index_key, time(), delivery_tag) \
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/Users/apple/Desktop/Study/celery-test/env/lib/python3.7/site-packages/redis/_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'float' object has no attribute 'items'
```

**Comment by kimdoori** [comment]
Solution: Roll back redis with pip:` pip install redis==2.10.6`
